# 新規ユーザ作成
# api/create
# POST http://127.0.0.1:8000/api/create/ HTTP/1.1
# content-type: application/json

# {
#     "username":"user1",
#     "password":"user1"
# }

# jwtの発行
POST http://127.0.0.1:8000/authen/jwt/create HTTP/1.1
content-type: application/json

{
    "username":"user1",
    "password":"user1"
}
